# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Acautico 12
email: vargas.ejido.96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog de Acautico12 para la asignatura de IAW del IES CELIA VIÑAS
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Miguel_Pollo_96
github_username:  Acautico12

# Build settings
markdown: kramdown
